name: Release package
on:
  push:
    branches: dev
jobs:
  build:
    name: Release on ${{ matrix.os }} for version ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14, ubuntu-latest]
        go: ["1.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Build
        run: go build main.go
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v1.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_MESSAGE: "PR available for merging"
