name: Release package
on: [push]
jobs:
  build:
    name: Release
    strategy:
      matrix:
        os: [macOS-10.14, windows-2016, ubuntu-18.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        uses: cedrickring/golang-action@1.4.1
