name: Build package
on:
  push:
    branches: dev
jobs:
  build:
    name: Release on ${{ matrix.os }} for version ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: ["1.15"]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Run tests
        run: |
          cd internal/deploy
          go test ./... -p 1
          cd ../..
      - name: Build
        run: go build main.go
