name: Release package
on: [push]
jobs:
  build:
    name: Release on ${{ matrix.os }} for version: ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14, ubuntu-latest]
        go: ["1.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Build
        run: go build main.go
