name: Release package
on:
  push:
    branches: master
jobs:
  build:
    name: Release on ${{ matrix.os }} for version ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: ["1.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
