name: Release package
on:
  push:
    branches: master
jobs:
  build:
    name: Release on ${{ matrix.os }} for version ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: ["1.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Bump version and push tag
        id: create_tag
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.new_tag  }}
          release_name: Release ${{ steps.create_tag.outputs.new_tag  }}
          draft: false
          prerelease: false
  deploy:
    name: Deploy Docker image to Github Registry
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build Docker image
        run: |
          docker login docker.pkg.github.com -u karbonn -p ${{ secrets.GH_TOKEN }}
          docker build -t docker.pkg.github.com/karbonn/karna/karna:latest
      - name: Deploy Docker image
        run: docker push docker.pkg.github.com/karbonn/karna/karna:latest
