name: Release package
on:
  push:
    branches: master
jobs:
  deploy:
    name: Release on ${{ matrix.os }} for version ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: ["1.15"]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build Docker image
        run: |
          docker login docker.pkg.github.com -u karbonn --password-stdin ${{ secrets.GITHUB_TOKEN }}
          docker build -t docker.pkg.github.com/karnalab/karna/karna:latest .
      - name: Deploy Docker image
        run: docker push docker.pkg.github.com/karnalab/karna/karna:latest
