name: Release package
on:
  push:
    branches: master
jobs:
  build:
    name: Release on ${{ matrix.os }} for version ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: ["1.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Login to Docker
        run: docker login docker.pkg.github.com --username karbonn
      - name: Build Docker Image
        run: |
          docker build -t karna/latest .
      - name: Tag Docker image
        run: docker tag karna/latest docker.pkg.github.com/karbonn/karna/karna:latest
      - name: Deploy Docker image
        run: docker push docker.pkg.github.com/karbonn/karna/karna:latest