name: Release package
on:
  push:
    tags:
      - v*
jobs:
  deploy:
    name: Release on ${{ matrix.os }} for version ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: ["1.15"]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: karbonn
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: docker build -t docker.pkg.github.com/karnalab/karna/karna:latest .
      - name: Deploy Docker image
        run: docker push docker.pkg.github.com/karnalab/karna/karna:latest
