name: Release
on:
  push:
    tags:
      - v*
jobs:
  deploy:
    name: Release on ${{ matrix.os }} for version ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: ["1.15"]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Deploy Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: karnalab/karna
          tag_with_ref: true
